# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cde88eb1d279ab3795d3caaa8857ae594fdb30bf0ed76b1fdf27cc6435a5c68b47c7d5026ebab16f8a9c50472999689b44a3bcd4e5b9f627be859c44837a61fc

test:
  secret_key_base: 6c48164e3e4bbe247ceb9527b8753265c6cda775781e0e21ce00f41f8fdf6dea6682298ef11cdce3991883e2c3d4da05f45de3cdaa3308ec18bcb530eb5e19f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
